---
apiVersion: v2

type: application

name: google-tag-manager
description: A Helm Chart for Google Tag Manager

version: "0.4.1"
appVersion: "1.17.0"

keywords:
  - google
  - tag
  - manager
  - tagmanager
  - analytics
  - advertising

home: https://github.com/trackify-info/helm-google-tag-manager
icon: https://www.gstatic.com/analytics-suite/header/suite/v2/ic_tag_manager.svg

sources:
  - https://github.com/trackify-info/helm-google-tag-manager

maintainers:
  - name: Matthias Klier
    email: mklier@trackify.info
